version: '3.8'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  instituto-service:
    build: ./instituto-service
    container_name: instituto-service
    ports:
      - "8081:8081"
    depends_on:
      - keycloak

  matricula-service:
    build: ./matricula-service
    container_name: matricula-service
    ports:
      - "8082:8082"
    depends_on:
      - keycloak

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8085:8085"
    depends_on:
      - instituto-service
      - matricula-service
      - keycloak